configfile: "./inputs/configs/batch4.json"

include: "rules/common.smk"
include: "rules/preprocess.smk"
rule all:
    params:
        batch = config["Metadata_Batch"]
    input:
        "outputs/batch_profiles/{params.batch}/filtered_wellpos_mad_featselect.parquet"